# Generated by Django 4.1.2 on 2022-10-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeseriesmata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('scalar', models.IntegerField()),
                ('Length', models.IntegerField()),
                ('SamplingPeriod', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Timesetmatadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=255)),
                ('setdiscription', models.CharField(max_length=255)),
                ('applicationdomain', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='timeseriesdata',
            old_name='SamplingPeriod',
            new_name='magnitude',
        ),
        migrations.RenameField(
            model_name='timeseriesdata',
            old_name='Length',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='scalar',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='tsname',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='units',
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
