# Generated by Django 4.1.2 on 2022-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastingapp', '0002_timeseriesmata_timesetmatadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriesmata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timesetmatadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='timeseriesmata',
            name='tsname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timesetmatadata',
            name='setname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
