# Generated by Django 4.1.2 on 2022-10-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('scalar', models.IntegerField()),
                ('Length', models.IntegerField()),
                ('SamplingPeriod', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
