# Generated by Django 4.1.2 on 2022-10-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecastingapp', '0003_remove_timeseriesmata_id_remove_timesetmatadata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.IntegerField()),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeseriesData',
        ),
        migrations.DeleteModel(
            name='Timesetmatadata',
        ),
        migrations.RenameModel(
            old_name='Timeseriesmata',
            new_name='Tsmetadata',
        ),
        migrations.AddField(
            model_name='tsdata',
            name='tstime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forecastingapp.tsmetadata'),
        ),
    ]
